config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#front'

  get 'ui(/:action)', controller: 'ui'

  resources :users, only: [:new, :create, :show]

  get '/sign_in', to: 'sessions#new'
  post '/sign_in', to: 'sessions#create'
  get '/sign_out', to: 'sessions#destroy'

  get '/auth/:provider/callback' => 'authentications#create'
end

app/models/authentication.rb
class Authentication
  include Mongoid::Document
  field :user_id, type: String
  field :provider, type: String
  field :uid, type: String
  embedded_in :users
end

app/models/user.rb
class User
  include Mongoid::Document
  include ActiveModel::SecurePassword

  field :first_name, type: String
  field :last_name, type: String
  field :email, type: String
  field :password_digest, type: String
  embeds_many :authentications

  has_secure_password validations: false

  validates_presence_of :first_name, :last_name, :email, :password
  validates_uniqueness_of :email
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.where(id: session[:user_id]['$oid']).first if session[:user_id]
  end

  def logged_in?
    !!current_user
  end
end

app/controllers/authentications_controller.rb
class AuthenticationsController < ApplicationController
  def index
  end

  def create
    auth_hash = request.env['omniauth.auth']
    current_user.authentications.find_or_create_by(provider: auth_hash['provider'], uid: auth_hash['uid'], user_id: current_user.id.to_s)
    flash[:success] = "You are now signed in"
    redirect_to user_path(current_user)
  end

  def destroy
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def front
    @user = User.new
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])

    if user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Thanks for signing in #{user.first_name}"
      redirect_to user_path(user)
    else
      flash[:danger] = "Oops! You messed up your info. Try again."
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = "You are now signed out."
    redirect_to root_path
  end
end

app/controllers/ui_controller.rb
class UiController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)


    if @user.save
      flash[:success] = "You have successfully signed up!"
      redirect_to user_path(@user)
    else
      flash[:danger] = "Oops, something went wrong with your info. Please try again."
      render 'pages/front'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cleansheets</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

  <header>
    <%= render 'shared/navigation' %>
  </header>

  <section class="content clearfix">
    <%= render 'shared/messages' %>
    <%= yield %>
  </section>

  <footer>
    A
    <%= link_to "Cullen Jett", 'http://www.cullenjett.com' %>
    Joint
  </footer>

</body>
</html>

app/views/pages/front.html.haml
.jumbotron
  .container-fluid
    .row
      .col-sm-10.col-sm-offset-1
        .intro-area
          %h1.text-center WELCOME HOME
          %h4.text-center Rent unique places to stay from local hosts in 190 countries.
          %button.center-block.btn How It Works
    .row
      .col-sm-12.bottom-search-area
        %form.form-inline.text-center
          %input.form-control{ :type => "text", :placeholder => "Where do you want to go?" }
          %input.form-control{ :type => "date" }
          %input.form-control{ :type => "date" }
          %select.form-control
            %option 1 Guest
            %option 2 Guests
          %button.btn{ :type => "submit" } Search

app/views/shared/_messages.html.haml
- flash.each do |name, msg|
  %div(class="alert alert-#{name}")
    %a.close(data-dismiss='alert') &#215;
    = content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String)

app/views/shared/_modal.html.haml
#sign-up-modal.modal.fade{"tab-index" => "-1", "role" => "dialog"}
  .modal-dialog.modal-sm
    .modal-content
      .modal-body
        %button.close{:type => "button", "data-dismiss" => "modal"}
          %span &times
          %span.sr-only Close
        = bootstrap_form_for @user do |f|
          = f.text_field :first_name, hide_label: true, class: "form-control", placeholder: "First Name"
          = f.text_field :last_name, hide_label: true, class: "form-control", placeholder: "Last Name"
          = f.email_field :email, hide_label: true, class: "form-control", placeholder: "Email"
          = f.password_field :password, hide_label: true, class: "form-control", placeholder: "Password"
          = f.submit "Sign Up", class: "btn"

app/views/shared/_navigation.html.haml
%nav.navbar.navbar-default{:role => "navigation"}
  .container-fluid
    / Brand and toggle get grouped for better mobile display
    .navbar-header
      %button.navbar-toggle{"data-target" => "#collapsed-section", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      %a.navbar-brand{:href => "#"} CleanSheets
    / Collect the nav links, forms, and other content for toggling
    #collapsed-section.collapse.navbar-collapse
      %ul.nav.navbar-nav.navbar-right
        - unless logged_in?
          %li
            = link_to "Sign Up", new_user_path
          %li
            = link_to "Log In", sign_in_path
        - else
          %li
            = link_to "Sign Out", sign_out_path
        %li
          %button.btn.navbar-btn List Your Space

app/views/ui/index.html.haml
%section.ui-index
  %ul
    - Dir.glob('app/views/ui/*.html.haml').sort.each do |file|
      - wireframe = File.basename(file,'.html.haml')
      -  unless wireframe == 'index' || wireframe.match(/^_/)
        %li= link_to wireframe.titleize, action: wireframe unless wireframe == 'index'

app/views/users/new.html.haml
.container
  .row
    .col-sm-6.col-sm-offset-3
      = bootstrap_form_for @user do |f|
        = f.text_field :first_name, hide_label: true, class: "form-control", placeholder: "First Name"
        = f.text_field :last_name, hide_label: true, class: "form-control", placeholder: "Last Name"
        = f.email_field :email, hide_label: true, class: "form-control", placeholder: "Email"
        = f.password_field :password, hide_label: true, class: "form-control", placeholder: "Password"
        = f.submit "Sign Up", class: "btn"

app/views/users/show.html.haml
%h1= "Hello #{@user.first_name}"
%p This is the user/show page